CREATE TABLE IF NOT EXISTS public.android_bg_v2
(
    id BIGSERIAL,
    report_id numeric,
    trigger_name character varying(100) COLLATE pg_catalog."default",
    result_date timestamp without time zone,
    received_date timestamp without time zone,
    received_date_local timestamp without time zone,
    time_zone_name character varying(100) COLLATE pg_catalog."default",
    device_id numeric,
    device_model character varying(255) COLLATE pg_catalog."default",
    device_manufacturer character varying(255) COLLATE pg_catalog."default",
    device_model_raw character varying(255) COLLATE pg_catalog."default",
    device_manufacturer_raw character varying(255) COLLATE pg_catalog."default",
    device_brand_raw character varying(255) COLLATE pg_catalog."default",
    os_version character varying(20) COLLATE pg_catalog."default",
    app_version character varying(11) COLLATE pg_catalog."default",
    connection_type numeric,
    is_airplane_mode character varying(7) COLLATE pg_catalog."default",
    is_network_roaming boolean,
    is_international_roaming boolean,
    number_registered_networks numeric,
    number_unregistered_networks numeric,
    sim_operator_name character varying(255) COLLATE pg_catalog."default",
    raw_sim_operator_name character varying(255) COLLATE pg_catalog."default",
    sim_operator_mcc_code numeric,
    sim_operator_mnc_code numeric,
    network_operator_name character varying(255) COLLATE pg_catalog."default",
    network_operator_mcc_code numeric,
    network_operator_mnc_code numeric,
    client_latitude numeric,
    client_longitude numeric,
    altitude numeric,
    location_accuracy numeric,
    location_age numeric,
    location_type numeric,
    country character varying(100) COLLATE pg_catalog."default",
    region character varying(100) COLLATE pg_catalog."default",
    subregion character varying(100) COLLATE pg_catalog."default",
    locality character varying(100) COLLATE pg_catalog."default",
    place_type character varying(100) COLLATE pg_catalog."default",
    postal_code character varying(100) COLLATE pg_catalog."default",
    computed_cellular_generation character varying(45) COLLATE pg_catalog."default",
    tac numeric,
    pci numeric,
    cell_identifier numeric,
    lte_enodeb numeric,
    rnc_id numeric,
    cell_id numeric,
    arfcn numeric,
    uarfcn numeric,
    earfcn numeric,
    is_primary_cell character varying(7) COLLATE pg_catalog."default",
    rsrp numeric,
    rsrq numeric,
    rssi numeric,
    rssnr numeric,
    timing_advance numeric,
    cqi numeric,
    wifi_enabled character varying(7) COLLATE pg_catalog."default",
    wifi_state numeric,
    wifi_rssi numeric,
    wifi_frequency numeric,
    wifi_channel numeric,
    app_foreground character varying(7) COLLATE pg_catalog."default",
    azimuth numeric,
    battery_level character varying(11) COLLATE pg_catalog."default",
    battery_level_max numeric,
    battery_plugged character varying(7) COLLATE pg_catalog."default",
    battery_present character varying(7) COLLATE pg_catalog."default",
    battery_status numeric,
    battery_technology character varying(255) COLLATE pg_catalog."default",
    battery_temperature numeric,
    battery_voltage numeric,
    device_idle_mode character varying(7) COLLATE pg_catalog."default",
    humidity numeric,
    humidity_accuracy character varying(7) COLLATE pg_catalog."default",
    light_lx numeric,
    light_accuracy character varying(7) COLLATE pg_catalog."default",
    pitch numeric,
    power_interactive character varying(7) COLLATE pg_catalog."default",
    power_save_mode character varying(7) COLLATE pg_catalog."default",
    pressure_accuracy character varying(7) COLLATE pg_catalog."default",
    pressure_mbar numeric,
    temp_celsius numeric,
    temp_accuracy character varying(7) COLLATE pg_catalog."default",
    grant_billing character varying(7) COLLATE pg_catalog."default",
    grant_internet character varying(7) COLLATE pg_catalog."default",
    grant_network_state character varying(7) COLLATE pg_catalog."default",
    grant_phone_state character varying(7) COLLATE pg_catalog."default",
    grant_fine_location character varying(7) COLLATE pg_catalog."default",
    grant_coarse_location character varying(7) COLLATE pg_catalog."default",
    grant_background_location character varying(7) COLLATE pg_catalog."default",
    grant_wifi_state character varying(7) COLLATE pg_catalog."default",
    grant_boot_completed character varying(7) COLLATE pg_catalog."default",
    valid_device_check character varying(7) COLLATE pg_catalog."default",
    location_check character varying(7) COLLATE pg_catalog."default",
    radio character varying(255) COLLATE pg_catalog."default",
    service_state character varying(32) COLLATE pg_catalog."default",
    sim_state character varying(32) COLLATE pg_catalog."default",
    sim_count character varying(7) COLLATE pg_catalog."default",
    guid character varying(32) COLLATE pg_catalog."default",
    cell_bandwidth numeric,
    vertical_accuracy numeric,
    nr_ss_rsrp numeric,
    nr_ss_rsrq numeric,
    nr_ss_sinr numeric,
    nr_csi_rsrp numeric,
    nr_csi_rsrq numeric,
    nr_csi_sinr numeric,
    nr_level numeric,
    nr_asu numeric,
    nr_arfcn numeric,
    nr_nci numeric,
    nr_pci numeric,
    nr_tac numeric,
    nr_mcc character varying(7) COLLATE pg_catalog."default",
    nr_mnc character varying(7) COLLATE pg_catalog."default",
    nr_state numeric,
    nr_frequency_range numeric,
    is_nr_available character varying(7) COLLATE pg_catalog."default",
    is_nr_telephony_sourced character varying(7) COLLATE pg_catalog."default",
    is_using_carrier_aggregation character varying(7) COLLATE pg_catalog."default",
    chipset_name character varying(255) COLLATE pg_catalog."default",
    chipset_manufacturer character varying(255) COLLATE pg_catalog."default",
    cell_bandwidths character varying(255) COLLATE pg_catalog."default",
    is_access_network_technology_nr character varying(7) COLLATE pg_catalog."default",
    device_tac numeric,
    downstream_bandwidth_kbps numeric,
    wifi_channel_width numeric,
    has_bg_location_permission character varying(7) COLLATE pg_catalog."default",
    has_cellular_service character varying(7) COLLATE pg_catalog."default",
    upstream_bandwidth_kbps numeric,
    gsm_additional_plmns character varying(255) COLLATE pg_catalog."default",
    tdscdma_additional_plmns character varying(255) COLLATE pg_catalog."default",
    wcdma_additional_plmns character varying(255) COLLATE pg_catalog."default",
    lte_additional_plmns character varying(255) COLLATE pg_catalog."default",
    lte_bands character varying(255) COLLATE pg_catalog."default",
    nr_additional_plmns character varying(255) COLLATE pg_catalog."default",
    nr_bands character varying(255) COLLATE pg_catalog."default",
    gsm_rssi numeric,
    wcdma_ecno numeric,
    wifi_rx_link_speed numeric,
    wifi_max_supported_rx_link_speed numeric,
    wifi_max_supported_tx_link_speed numeric,
    wifi_passpoint_fqdn character varying(255) COLLATE pg_catalog."default",
    wifi_passpoint_provider_name character varying(255) COLLATE pg_catalog."default",
    wifi_carrier_name character varying(255) COLLATE pg_catalog."default",
    wifi_standard numeric,
    wifi_is_2_4GHz_band_supported character varying(7) COLLATE pg_catalog."default",
    wifi_is_6GHz_band_supported character varying(7) COLLATE pg_catalog."default",
    wifi_is_60GHz_band_supported character varying(7) COLLATE pg_catalog."default",
    current_thermal_status numeric,
    thermal_headroom numeric,
    alt_sim_operator_name character varying(255) COLLATE pg_catalog."default",
    alt_raw_sim_operator_name character varying(255) COLLATE pg_catalog."default",
    alt_sim_operator_mcc_code numeric,
    alt_sim_operator_mnc_code numeric,
    data_activity numeric,
    data_state numeric,
    display_state numeric,
    is_concurrent_voice_data_supported character varying(7) COLLATE pg_catalog."default",
    is_data_capable character varying(7) COLLATE pg_catalog."default",
    is_data_enabled character varying(7) COLLATE pg_catalog."default",
    is_data_connection_allowed character varying(7) COLLATE pg_catalog."default",
    is_data_roaming_enabled character varying(7) COLLATE pg_catalog."default",
    has_icc_card character varying(7) COLLATE pg_catalog."default",
    is_world_phone character varying(7) COLLATE pg_catalog."default",
    is_multi_sim_supported numeric,
    active_modem_count numeric,
    supported_modem_count numeric,
    override_network_type numeric,
    lac numeric,
    psc numeric,
    CONSTRAINT android_bg_v2_id_seq_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS android_bg_v2_received_date_idx
    ON public.android_bg_v2 USING btree
    (received_date ASC NULLS LAST)
    TABLESPACE pg_default;

